---
title: Excluyendo patrones de una sustitución de expresiones regulares con Python
hero_image: images/banner.png
description: Excluyendo patrones de sustituciones de expresiones regulares
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - title: Introducción

